name: Add PR to GitHub Project (Ready to review)

on:
  pull_request:
    types: [opened]

jobs:
  add-to-project:
    runs-on: ubuntu-latest
    steps:
      - name: Install GitHub CLI and Projects v2 extension
        run: |
          sudo apt update && sudo apt install gh -y
          gh extension install github/gh-projects

      - name: Authenticate GitHub CLI
        run: echo "${{ secrets.MY_PROJECT_TOKEN }}" | gh auth login --with-token

      - name: Add PR to project
        run: |
          gh projectv2 item-add \
            --owner Utkarsh-123github \
            --number 1 \
            --url "https://github.com/${{ github.repository }}/pull/${{ github.event.pull_request.number }}"

      - name: Set status to "Ready to review"
        run: |
          PR_URL="https://github.com/${{ github.repository }}/pull/${{ github.event.pull_request.number }}"
          gh projectv2 item-list \
            --owner Utkarsh-123github \
            --number 1 \
            --format json > items.json

          ITEM_ID=$(grep -B 1 "$PR_URL" items.json | grep '"id"' | head -n 1 | sed 's/[^"]*"\([^"]*\)".*/\1/')

          echo "Found item ID: $ITEM_ID"

          gh projectv2 item-edit \
            --id "$ITEM_ID" \
            --field-id PVTSSF_lAHOBtVIJM4A6Ub7zgu8tMM \
            --single-select-option-id f75ad846
