name: Add PR to Project (Ready to review)

on:
  pull_request:
    types: [opened]

jobs:
  add-to-project:
    runs-on: ubuntu-latest
    steps:
      - name: Install GitHub CLI
        run: sudo apt update && sudo apt install gh -y

      - name: Authenticate GitHub CLI
        run: echo "${{ secrets.MY_PROJECT_TOKEN }}" | gh auth login --with-token

      - name: Add PR to project in "Ready to review" column
        run: |
          PR_URL="https://github.com/${{ github.repository }}/pull/${{ github.event.pull_request.number }}"

          # Add the PR to the project
          gh project item-add \
            --project-id PVT_kwHOBtVIJM4A6Ub7 \
            --url "$PR_URL"

          # Wait a few seconds to ensure item is added before fetching it
          sleep 5

          # Find the item ID (without jq)
          ITEM_ID=$(gh project item-list --project-id PVT_kwHOBtVIJM4A6Ub7 --format json | grep -B 1 "$PR_URL" | grep '"id"' | head -n 1 | sed 's/[^"]*"\([^"]*\)".*/\1/')

          # Set status to "Ready to review"
          gh project item-edit "$ITEM_ID" \
            --project-id PVT_kwHOBtVIJM4A6Ub7 \
            --field-id PVTSSF_lAHOBtVIJM4A6Ub7zgu8tMM \
            --value-id f75ad846
